import React, {Component} from 'react';
// import { Card, Form ,Row, Col, Button} from 'react-bootstrap'
// import { Dropdown } from 'react-bootstrap';
import './Learner.css' ;

import { Card, Button, Form, Container, Col, Row, Dropdown, ProgressBar } from 'react-bootstrap'
// import DropdownToggle from 'react-bootstrap/esm/DropdownToggle'

export default class AddLearner extends Component {
    render () { 
      return (
          <Card className="AddLearner">
            <Card.Body>
              <Card.Title>Add Learner</Card.Title>
              <Card.Text>
              <Form>
            <Form.Group className="mb-3" controlId="formBasicName"> 
              <Container>
                <Form.Group as={Row} className="mb-3" controlId="requestid">
                    <Form.Label column sm="6">Request Id</Form.Label>
                    <Col sm="5">
                      <Form.Control type="text" placeholder="Autogenerated Request Id" readOnly />
                    </Col>
                  </Form.Group>
                  <Form.Group as={Row} className="mb-3" controlId="userid">
                    <Form.Label column sm="6">User Id</Form.Label>
                    <Col sm="5">
                      <Form.Control type="text" placeholder="Enter User Id"  />
                    </Col>
                  </Form.Group>
                  <Form.Group as={Row} className="mb-3" controlId="role">
                    <Form.Label column sm="6">Role / Name</Form.Label>
                    <Col sm="5">
                      <Form.Select defaultValue="Select">
                        <option>Select</option>
                        <option>Learner</option>
                        <option>Mentor</option>

                      </Form.Select>
                    </Col>
                  </Form.Group>
                {/* <Row>
                  <Col><font color="Green"><Form.Label>Role</Form.Label></font></Col>
                  <Col><Dropdown>
                    <Dropdown.Toggle variant="Success" role="dropdown-basic">
                      Select Role of Learner
                    </Dropdown.Toggle>
                    <Dropdown.Menu>
                      <Dropdown.Item href="#/action-1">Learner</Dropdown.Item>
                      <Dropdown.Item href="#/action-2">Mentor</Dropdown.Item>
                    </Dropdown.Menu>

                  </Dropdown>
                  </Col>
                </Row> */}
                {/* <Row>
                  <Col><font color="Green"><Form.Label>Course Identification Number</Form.Label></font></Col>
                  <Col><Form.Control type="courseId" placeholder="Enter Course Id of Learner" /></Col>
                </Row> */}
                <Form.Group as={Row} className="mb-3" controlId="courseid">
                    <Form.Label column sm="6">Course Id</Form.Label>
                    <Col sm="5"><Form.Control type="text" placeholder="Enter Course Id"/></Col>
                  </Form.Group>
                {/* <Row>
                  <Col><font color="Green"><Form.Label>Reporting Manager Identification Number</Form.Label></font></Col>
                  <Col><Form.Control type="rmid" placeholder="Enter Reporting Manager Id of Learner" /></Col>
                </Row> */}
                <Form.Group as={Row} className="mb-3" controlId="rmid">
                    <Form.Label column sm="6">Reporting manager</Form.Label>
                    <Col sm="5">
                      <Form.Control type="text" placeholder="Enter RM Id/Name"  />
                    </Col>
                  </Form.Group>

                  <Form.Group as={Row} className="mb-3" controlId="courseId">
                    <Form.Label column sm="6">Course ID / Name</Form.Label>
                    <Col sm="5">
                      <Form.Select defaultValue="Select">
                        <option>Select</option>
                        <option>1. Core Java</option>
                        <option>2. Advance Java</option>
                        <option>3. React</option>
                      </Form.Select>
                    </Col>
                  </Form.Group>

                {/* <Row>
                  <Col><font color="Green"><Form.Label>Approval Identification Number</Form.Label></font></Col>
                  <Col><Form.Control type="approvalId" placeholder="Enter Approval Id of Learner" /></Col>
                </Row> */}
                <Form.Group as={Row} className="mb-3" controlId="approvalid">
                    <Form.Label column sm="6">Approval ID</Form.Label>
                    <Col sm="5">
                      <Form.Control type="text" value="01" readOnly/>
                    </Col>
                </Form.Group>

                {/* <Row>
                  <Col><font color="Green"><Form.Label>Approval Status</Form.Label></font></Col>
                  <Col><Dropdown>
                    <Dropdown.Toggle variant="Success" approvalStatus="dropdown-basic">
                      Select Approval Status of Learner
                    </Dropdown.Toggle>
                    <Dropdown.Menu>
                      <Dropdown.Item href="#/action-1">Initiated</Dropdown.Item>
                      <Dropdown.Item href="#/action-2">Approved</Dropdown.Item>
                      <Dropdown.Item href="#/action-2">Rejected</Dropdown.Item>
                    </Dropdown.Menu>
                  </Dropdown>
                  </Col>
                </Row> */}

                <Form.Group as={Row} className="mb-3" controlId="approvalstatus">
                    <Form.Label column sm="6">Approval Status</Form.Label>
                    <Col sm="5">
                      <Form.Control type="text" value="Initiated" readOnly/>
                    </Col>
                </Form.Group>
                {/* <Row>
                  <Col><font color="Green"><Form.Label>Assignment Identification Number</Form.Label></font></Col>
                  <Col><Form.Control type="assignmentId" placeholder="Enter Assignment Id of Learner" /></Col>
                </Row> */}
                <Form.Group as={Row} className="mb-3" controlId="assignmentid">
                    <Form.Label column sm="6">Assignment Id</Form.Label>
                    <Col sm="5">
                      <Form.Control type="text" value="TBC" readOnly/>
                    </Col>
                </Form.Group>
              
                
                  {/* <Col><font color="Green"><Form.Label>Assignment Status</Form.Label></font></Col>
                  <Col><Dropdown>
                    <Dropdown.Toggle variant="Success" assignmentStatus="dropdown-basic">
                      Select Assignment Status of Learner
                    </Dropdown.Toggle>
                    <Dropdown.Menu>
                      <Dropdown.Item href="#/action-1">Initiated</Dropdown.Item>
                      <Dropdown.Item href="#/action-2">Approved</Dropdown.Item>
                      <Dropdown.Item href="#/action-2">Rejected</Dropdown.Item>
                    </Dropdown.Menu>
                  </Dropdown>
                  </Col> */}
                  <Form.Group as={Row} className="mb-3" controlId="assignmentstatus">
                    <Form.Label column sm="6">Assignment Status</Form.Label>
                    <Col sm="5">
                      <Form.Control type="text" value="NA" readOnly/>
                    </Col>
                  </Form.Group>
                
                {/* <Row>
                  <Col><font color="Green"><Form.Label>Assignment Status Message</Form.Label></font></Col>
                  <Col><Form.Control type="assignmentStatusMessage" placeholder="Enter Assignment Status Message of Learner" /></Col>
                </Row> */}
                  <Form.Group as={Row} className="mb-3" controlId="assignmentstatusmessage">
                    <Form.Label column sm="6">Assignment Status Message</Form.Label>
                    <Col sm="5">
                      <Form.Control type="text" value="" readOnly/>
                    </Col>
                  </Form.Group>
                {/* <Row>
                  <Col><font color="Green"><Form.Label>Learner Description</Form.Label></font></Col>
                  <Col><Form.Control type="learnerDescription" placeholder="Enter Learner Description" /></Col>
                </Row> */}
                  <Form.Group as={Row} className="mb-3" controlId="learnerdescription">
                    <Form.Label column sm="6">Learner Description</Form.Label>
                    <Col sm="5">
                      <Form.Control type="text" value="New Learner" readOnly/>
                    </Col>
                  </Form.Group>
                {/* <Row>
                  <Col><font color="Green"><Form.Label>Learner Score</Form.Label></font></Col>
                  <Col><Form.Control type="learnerScore" placeholder="Enter Learner Score" /></Col>
                </Row> */}
                  <Form.Group as={Row} className="mb-3" controlId="learnerscore">
                    <Form.Label column sm="6">Learner Score</Form.Label>
                    <Col sm="5">
                      <Form.Control type="text" value="0" readOnly/>
                    </Col>
                  </Form.Group>
              </Container>
              {/* <Form.Text className="text-muted">
                Learner stuff :)
              </Form.Text> */}
            </Form.Group>
            <div className ="d-grid">
            <Button variant="primary" onClick={this.addNewLearner}>
              Submit
            </Button>
            </div>
          </Form>
                
              
              </Card.Text>
            </Card.Body>
          </Card>
 
  )
}

addNewLearner(){
   return (
    console.log('Add clicked')
    //  <h1>
    //  <div className="ViewLearnerList"> 
    //    display details here      
    //  </div>  
    //  </h1>

  

  )
  
}

validateUser(){
  return (
    console.log('Validate user')
    //  <h1>
    //  <div className="ViewLearnerList"> 
    //    display details here      
    //  </div>  
    //  </h1>

  

  )

}
}